### ISSUE TITLE
测试-徐

### ISSUE THREAD

**Issue by LiChunyu77** [ccnu-lab/project-cac#23]

**Comment by Jasmineff15** [comment]
get
&nbsp;


Jasmine
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月9日(星期四) 下午2:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ccnu-lab/project-cac] 测试-徐 (Issue #23)





 
Assigned #23 to @Jasmineff15.
